import type { Metadata } from 'next'
import CodeBlock from '@/app/_components/code-block'

export const metadata: Metadata = {
  title: 'CLI — Thingspire UI',
  description:
    '@309-thingspire/ui CLI reference: init, add, list, registry URLs, environment variables.',
}

export default function CliPage() {
  return (
    <main className="container" style={{ paddingBlock: 48, maxWidth: 980 }}>
      <header style={{ marginBottom: 40 }}>
        <p
          style={{
            fontSize: 12,
            color: 'hsl(var(--muted-foreground))',
            textTransform: 'uppercase',
            letterSpacing: '0.04em',
            margin: 0,
          }}
        >
          Reference
        </p>
        <h1
          className="comp-detail__title"
          style={{ marginTop: 8, marginBottom: 12 }}
        >
          @309-thingspire/ui CLI
        </h1>
        <p className="comp-detail__lead">
          Copies component source, types, and tokens into your project. No
          runtime dependency &mdash; once installed the files are yours to edit.
        </p>
      </header>

      <section
        id="install"
        className="comp-detail__section"
        style={{ scrollMarginTop: 80 }}
      >
        <h2 className="comp-detail__section-title">Quick start</h2>
        <p className="comp-detail__section-desc">
          From the root of any React 19 project:
        </p>
        <div style={{ display: 'grid', gap: 12 }}>
          <CodeBlock code="npx @309-thingspire/ui@latest init" language="bash" />
          <CodeBlock
            code="npx @309-thingspire/ui@latest add button checkbox input"
            language="bash"
          />
          <CodeBlock code="npx @309-thingspire/ui@latest add icons" language="bash" />
        </div>
      </section>

      <section
        id="commands"
        className="comp-detail__section"
        style={{ scrollMarginTop: 80 }}
      >
        <h2 className="comp-detail__section-title">Commands</h2>
        <div style={{ overflowX: 'auto' }}>
          <table className="props-table">
            <thead>
              <tr>
                <th style={{ minWidth: 180 }}>Command</th>
                <th>What it does</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><code>init</code></td>
                <td>
                  Create a <code>design-library.json</code> at the cwd with
                  registry URL, components dir, and tokens path.
                </td>
              </tr>
              <tr>
                <td><code>add &lt;slug…&gt;</code></td>
                <td>
                  Fetch one or more components from the registry into
                  <code style={{ marginInline: 4 }}>componentsDir</code>. On
                  conflict, existing files are skipped unless{' '}
                  <code>--overwrite</code> is passed.
                </td>
              </tr>
              <tr>
                <td><code>list</code></td>
                <td>
                  Print every available slug grouped by category
                  (atoms / molecules / organisms).
                </td>
              </tr>
              <tr>
                <td><code>help</code></td>
                <td>Print command reference.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section
        id="flags"
        className="comp-detail__section"
        style={{ scrollMarginTop: 80 }}
      >
        <h2 className="comp-detail__section-title">Flags &amp; environment</h2>
        <div style={{ overflowX: 'auto' }}>
          <table className="props-table">
            <thead>
              <tr>
                <th style={{ minWidth: 240 }}>Name</th>
                <th>Effect</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><code>--registry &lt;url&gt;</code></td>
                <td>Override registry URL for this invocation.</td>
              </tr>
              <tr>
                <td><code>--overwrite</code></td>
                <td>
                  Replace existing local files when running <code>add</code>{' '}
                  (default: skip on conflict).
                </td>
              </tr>
              <tr>
                <td><code>THINGSPIRE_UI_REGISTRY</code></td>
                <td>Environment variable that overrides the registry URL globally.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section
        id="config"
        className="comp-detail__section"
        style={{ scrollMarginTop: 80 }}
      >
        <h2 className="comp-detail__section-title">design-library.json</h2>
        <p className="comp-detail__section-desc">
          Generated by <code>init</code>. Edit any field if your project layout
          differs &mdash; the CLI reads it on every <code>add</code>.
        </p>
        <CodeBlock
          language="json"
          code={`{
  "registry": "https://thingspire-dsg.vercel.app/r",
  "componentsDir": "components",
  "tokensCss": "styles/tokens.css"
}`}
        />
      </section>

      <section
        id="registry"
        className="comp-detail__section"
        style={{ scrollMarginTop: 80 }}
      >
        <h2 className="comp-detail__section-title">Registry endpoints</h2>
        <p className="comp-detail__section-desc">
          Static JSON mirrors are served from the CDN; the same shape is also
          available from a Next.js API route as a fallback.
        </p>
        <div style={{ overflowX: 'auto' }}>
          <table className="props-table">
            <thead>
              <tr>
                <th style={{ minWidth: 280 }}>URL</th>
                <th>Content</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><code>/r/index.json</code></td>
                <td>
                  Array of <code>{'{ slug, label, category, description }'}</code>
                </td>
              </tr>
              <tr>
                <td><code>/r/&lt;slug&gt;.json</code></td>
                <td>
                  Full bundle:{' '}
                  <code>{'{ name, slug, files: [{ path, type, content }], dependencies, registryDependencies }'}</code>
                </td>
              </tr>
              <tr>
                <td><code>/r/icons.json</code></td>
                <td>
                  IconLibrary metadata + every generated{' '}
                  <code>icon-*.tsx</code> + barrel <code>index.ts</code> /{' '}
                  <code>types.ts</code> in one bundle.
                </td>
              </tr>
              <tr>
                <td><code>/api/registry</code></td>
                <td>Same shape as <code>/r/index.json</code>.</td>
              </tr>
              <tr>
                <td><code>/api/registry/&lt;slug&gt;</code></td>
                <td>Same shape as <code>/r/&lt;slug&gt;.json</code>.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section
        id="examples"
        className="comp-detail__section"
        style={{ scrollMarginTop: 80 }}
      >
        <h2 className="comp-detail__section-title">Examples</h2>

        <h3 style={{ fontSize: 16, fontWeight: 600, marginTop: 16 }}>
          Add a curated set
        </h3>
        <CodeBlock
          language="bash"
          code="npx @309-thingspire/ui add button checkbox input dropdown badge"
        />

        <h3 style={{ fontSize: 16, fontWeight: 600, marginTop: 24 }}>
          Refresh after the upstream library updated
        </h3>
        <CodeBlock language="bash" code="npx @309-thingspire/ui add button --overwrite" />

        <h3 style={{ fontSize: 16, fontWeight: 600, marginTop: 24 }}>
          Pin to a specific deployment
        </h3>
        <p className="comp-detail__section-desc">
          Each Vercel deployment keeps its own immutable URL. Set the env var
          to lock against drift:
        </p>
        <CodeBlock
          language="bash"
          code={`export THINGSPIRE_UI_REGISTRY=https://thingspire-<deployment>.vercel.app/r
npx @309-thingspire/ui add button`}
        />

        <h3 style={{ fontSize: 16, fontWeight: 600, marginTop: 24 }}>
          Inspect what a slug ships
        </h3>
        <CodeBlock
          language="bash"
          code={`curl -s https://thingspire-dsg.vercel.app/r/button.json | jq '.files[] | .path'`}
        />
      </section>
    </main>
  )
}
