// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-up-line.svg

import type { SVGProps } from 'react'

export function IconArrowUpLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12.9999 7.828V20H10.9999V7.828L5.63592 13.192L4.22192 11.778L11.9999 4L19.7779 11.778L18.3639 13.192L12.9999 7.828Z" fill="currentColor"/>
    </svg>
  )
}
