// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-left-fill.svg

import type { SVGProps } from 'react'

export function IconArrowLeftFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12 13V20L4 12L12 4V11H20V13H12Z" fill="currentColor"/>
    </svg>
  )
}
