// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/signal-wifi-3-line.svg

import type { SVGProps } from 'react'

export function IconSignalWifi3Line(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11.9999 3C16.2839 3 20.2199 4.497 23.3099 6.996L11.9999 21L0.689941 6.997C3.77994 4.497 7.71394 3 11.9999 3ZM11.9999 10C10.1019 10 8.31694 10.48 6.75894 11.327L11.9989 17.817L17.2409 11.327C15.6829 10.48 13.8979 10 11.9999 10ZM11.9999 5C8.97194 5 6.07694 5.842 3.57994 7.392L5.48394 9.749C7.39994 8.637 9.62494 8 11.9999 8C14.3749 8 16.5999 8.637 18.5159 9.749L20.4199 7.39C17.9219 5.841 15.0269 5 11.9999 5Z" fill="currentColor"/>
    </svg>
  )
}
