// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-right-down-fill.svg

import type { SVGProps } from 'react'

export function IconArrowRightDownFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11.637 13.0505L5.97998 7.39547L7.39398 5.98047L13.051 11.6375L18 6.68747V18.0005H6.68698L11.637 13.0505Z" fill="currentColor"/>
    </svg>
  )
}
