// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-down-s-fill.svg

import type { SVGProps } from 'react'

export function IconArrowDownSFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12 16L6 10H18L12 16Z" fill="currentColor"/>
    </svg>
  )
}
