// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/css3-line.svg

import type { SVGProps } from 'react'

export function IconCss3Line(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M2.8 14H4.84L4.295 16.725L10.039 18.879L17.266 16.469L18.36 11H3.4L3.8 9H18.76L19.56 5H4.6L5 3H22L19 18L10 21L2 18L2.8 14Z" fill="currentColor"/>
    </svg>
  )
}
