// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-right-down-line.svg

import type { SVGProps } from 'react'

export function IconArrowRightDownLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M14.5899 16.0044L5.98193 7.3974L7.39593 5.9834L16.0029 14.5894V7.0044H18.0029V18.0044H7.00293V16.0044H14.5899Z" fill="currentColor"/>
    </svg>
  )
}
