// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/subtract-line.svg

import type { SVGProps } from 'react'

export function IconSubtractLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M5 11H19V13H5V11Z" fill="currentColor"/>
    </svg>
  )
}
