// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/door-fill.svg

import type { SVGProps } from 'react'

export function IconDoorFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M18 3C18.552 3 19 3.448 19 4V20C19 20.552 18.552 21 18 21H6C5.448 21 5 20.552 5 20V4C5 3.448 5.448 3 6 3H18ZM14 11C13.448 11 13 11.448 13 12C13 12.552 13.448 13 14 13C14.552 13 15 12.552 15 12C15 11.448 14.552 11 14 11Z" fill="currentColor"/>
    </svg>
  )
}
