// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/compass-2-fill.svg

import type { SVGProps } from 'react'

export function IconCompass2Fill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M18.328 4.258L10.586 12L12 13.414L19.742 5.672C21.2051 7.45601 22.0032 9.69276 22 12C22 17.52 17.52 22 12 22C6.48 22 2 17.52 2 12C2 6.48 6.48 2 12 2C14.4 2 16.604 2.847 18.328 4.258Z" fill="currentColor"/>
    </svg>
  )
}
