// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/upload-fill.svg

import type { SVGProps } from 'react'

export function IconUploadFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M3 19H21V21H3V19ZM13 10V18H11V10H4L12 2L20 10H13Z" fill="currentColor"/>
    </svg>
  )
}
