// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/expand-up-down.svg

import type { SVGProps } from 'react'

export function IconExpandUpDown(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M18 9L12 3L6 9H18ZM18 15L12 21L6 15H18Z" fill="currentColor"/>
    </svg>
  )
}
