// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/expand-left-right.svg

import type { SVGProps } from 'react'

export function IconExpandLeftRight(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M15 18L21 12L15 6L15 18ZM9 18L3 12L9 6L9 18Z" fill="currentColor"/>
    </svg>
  )
}
