// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-left-up-line.svg

import type { SVGProps } from 'react'

export function IconArrowLeftUpLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M9.414 8L18.021 16.607L16.607 18.021L8 9.414V17H6V6H17V8H9.414Z" fill="currentColor"/>
    </svg>
  )
}
