// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-down-line.svg

import type { SVGProps } from 'react'

export function IconArrowDownLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M13 16.172L18.364 10.808L19.778 12.222L12 20L4.22205 12.222L5.63605 10.808L11 16.172V4H13V16.172Z" fill="currentColor"/>
    </svg>
  )
}
