// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/download-fill.svg

import type { SVGProps } from 'react'

export function IconDownloadFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M3 19H21V21H3V19ZM13 9H20L12 17L4 9H11V1H13V9Z" fill="currentColor"/>
    </svg>
  )
}
