// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/voice-recognition-fill.svg

import type { SVGProps } from 'react'

export function IconVoiceRecognitionFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M21 3V21H3V3H21ZM13 6H11V18H13V6ZM9 9H7V15H9V9ZM17 9H15V15H17V9Z" fill="currentColor"/>
    </svg>
  )
}
