// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/pause-fill.svg

import type { SVGProps } from 'react'

export function IconPauseFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M6 5H8V19H6V5ZM16 5H18V19H16V5Z" fill="currentColor"/>
    </svg>
  )
}
