// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/creative-commons-nd-fill.svg

import type { SVGProps } from 'react'

export function IconCreativeCommonsNdFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12 2C17.523 2 22 6.477 22 12C22 17.523 17.523 22 12 22C6.477 22 2 17.523 2 12C2 6.477 6.477 2 12 2ZM16 13H8V15H16V13ZM16 9H8V11H16V9Z" fill="currentColor"/>
    </svg>
  )
}
