// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/scan-fill.svg

import type { SVGProps } from 'react'

export function IconScanFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M4.257 5.67101L12 13.414L13.414 12L5.671 4.25701C7.4555 2.7942 9.69257 1.99644 12 2.00001C17.523 2.00001 22 6.47701 22 12C22 17.523 17.523 22 12 22C6.477 22 2 17.523 2 12C2 9.59901 2.846 7.39501 4.257 5.67101Z" fill="currentColor"/>
    </svg>
  )
}
