// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/signal-wifi-fill.svg

import type { SVGProps } from 'react'

export function IconSignalWifiFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11.9999 3C16.2839 3 20.2199 4.497 23.3099 6.996L11.9999 21L0.689941 6.997C3.77994 4.497 7.71394 3 11.9999 3Z" fill="currentColor"/>
    </svg>
  )
}
