// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/angularjs-fill.svg

import type { SVGProps } from 'react'

export function IconAngularjsFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12 2L21.2999 5.32L19.882 17.63L12 22L4.11795 17.63L2.69995 5.32L12 2ZM12 4.21L6.18595 17.26H8.35395L9.52295 14.34H14.457L15.627 17.26H17.794L12 4.21ZM13.698 12.54H10.302L12 8.45L13.698 12.54Z" fill="currentColor"/>
    </svg>
  )
}
