// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/goblet-fill.svg

import type { SVGProps } from 'react'

export function IconGobletFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11 19V13.889L3 5V3H21V5L13 13.889V19H18V21H6V19H11ZM7.49 7H16.51L18.31 5H5.69L7.49 7Z" fill="currentColor"/>
    </svg>
  )
}
