// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/cursor-line.svg

import type { SVGProps } from 'react'

export function IconCursorLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M15.388 13.4981L17.94 20.5121L13.242 22.2221L10.689 15.2081L6.79004 17.6531L8.41004 1.63306L19.947 12.8651L15.389 13.4981H15.388ZM15.377 19.3161L12.662 11.8561L15.622 11.4461L9.98204 5.95606L9.19204 13.7861L11.722 12.1991L14.437 19.6591L15.377 19.3161Z" fill="currentColor"/>
    </svg>
  )
}
