// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/character-recognition-fill.svg

import type { SVGProps } from 'react'

export function IconCharacterRecognitionFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M21 3V21H3V3H21ZM12.999 6H10.999L6.6 17H8.754L9.953 14H14.043L15.244 17H17.399L12.999 6ZM11.999 8.885L13.244 12H10.752L11.999 8.885Z" fill="currentColor"/>
    </svg>
  )
}
