// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-right-s-fill.svg

import type { SVGProps } from 'react'

export function IconArrowRightSFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M16 12L10 18V6L16 12Z" fill="currentColor"/>
    </svg>
  )
}
