// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/text-spacing.svg

import type { SVGProps } from 'react'

export function IconTextSpacing(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M7 17H17V14.5L20.5 18L17 21.5V19H7V21.5L3.5 18L7 14.5V17ZM13 6V15H11V6H5V4H19V6H13Z" fill="currentColor"/>
    </svg>
  )
}
