// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/number-1.svg

import type { SVGProps } from 'react'

export function IconNumber1(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M14 1.5V22H12V3.704L7.5 4.91V2.839L12.5 1.5H14Z" fill="currentColor"/>
    </svg>
  )
}
