// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/fridge-fill.svg

import type { SVGProps } from 'react'

export function IconFridgeFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M20 12V22C20 22.552 19.552 23 19 23H5C4.448 23 4 22.552 4 22V12H20ZM9 14H7V19H9V14ZM19 1C19.552 1 20 1.448 20 2V10H4V2C4 1.448 4.448 1 5 1H19ZM9 4H7V8H9V4Z" fill="currentColor"/>
    </svg>
  )
}
