// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/zzz-line.svg

import type { SVGProps } from 'react'

export function IconZzzLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11 11V13L5.673 19H11V21H3V19L8.326 13H3V11H11ZM21 3V5L15.673 11H21V13H13V11L18.326 5H13V3H21Z" fill="currentColor"/>
    </svg>
  )
}
