// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/send-to-back.svg

import type { SVGProps } from 'react'

export function IconSendToBack(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11 3C11.552 3 12 3.448 12 4V6H17C17.552 6 18 6.448 18 7V12H20C20.552 12 21 12.448 21 13V20C21 20.552 20.552 21 20 21H13C12.448 21 12 20.552 12 20V18H7C6.448 18 6 17.552 6 17V12H4C3.448 12 3 11.552 3 11V4C3 3.448 3.448 3 4 3H11ZM16 8H12V11C12 11.552 11.552 12 11 12H8V16H12V13C12 12.448 12.448 12 13 12H16V8Z" fill="currentColor"/>
    </svg>
  )
}
