// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/rss-line.svg

import type { SVGProps } from 'react'

export function IconRssLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M3 17C4.06087 17 5.07828 17.4214 5.82843 18.1716C6.57857 18.9217 7 19.9391 7 21H3V17ZM3 10C9.075 10 14 14.925 14 21H12C12 18.6131 11.0518 16.3239 9.36396 14.636C7.67613 12.9482 5.38695 12 3 12V10ZM3 3C12.941 3 21 11.059 21 21H19C19 12.163 11.837 5 3 5V3Z" fill="currentColor"/>
    </svg>
  )
}
