// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/filter-fill.svg

import type { SVGProps } from 'react'

export function IconFilterFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M21 4V6H20L14 15V22H10V15L4 6H3V4H21Z" fill="currentColor"/>
    </svg>
  )
}
