// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/crop-2-fill.svg

import type { SVGProps } from 'react'

export function IconCrop2Fill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M17.586 5L20.142 2.444L21.556 3.858L19 6.414V17H22V19H19V22H17V7H9V5H17.586ZM15 17V19H6C5.73478 19 5.48043 18.8946 5.29289 18.7071C5.10536 18.5196 5 18.2652 5 18V7H2V5H5V2H7V17H15ZM9 9H15V15H9V9Z" fill="currentColor"/>
    </svg>
  )
}
