// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/text.svg

import type { SVGProps } from 'react'

export function IconText(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M13 6V21H11V6H5V4H19V6H13Z" fill="currentColor"/>
    </svg>
  )
}
