// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-up-s-fill.svg

import type { SVGProps } from 'react'

export function IconArrowUpSFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12 9L18 15H6L12 9Z" fill="currentColor"/>
    </svg>
  )
}
