// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-right-up-fill.svg

import type { SVGProps } from 'react'

export function IconArrowRightUpFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M13.05 12.3601L7.39398 18.0181L5.97998 16.6031L11.637 10.9471L6.68698 5.99707H18V17.3101L13.05 12.3601Z" fill="currentColor"/>
    </svg>
  )
}
