// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-drop-left-fill.svg

import type { SVGProps } from 'react'

export function IconArrowDropLeftFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M9 12L13 8V16L9 12Z" fill="currentColor"/>
    </svg>
  )
}
