// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/file-history-fill.svg

import type { SVGProps } from 'react'

export function IconFileHistoryFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M16 2L21 6.999V21.009C21 21.556 20.555 22 20.007 22H3.993C3.445 22 3 21.545 3 21.008V2.992C3 2.444 3.445 2 3.993 2H16ZM13 9H11V15H16V13H13V9Z" fill="currentColor"/>
    </svg>
  )
}
