// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/bring-forward.svg

import type { SVGProps } from 'react'

export function IconBringForward(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M14 3C14.552 3 15 3.448 15 4V9H20C20.552 9 21 9.448 21 10V20C21 20.552 20.552 21 20 21H10C9.448 21 9 20.552 9 20V15H4C3.448 15 3 14.552 3 14V4C3 3.448 3.448 3 4 3H14ZM13 5H5V13H13V5Z" fill="currentColor"/>
    </svg>
  )
}
