// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-left-down-line.svg

import type { SVGProps } from 'react'

export function IconArrowLeftDownLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M8 14.5904L16.607 5.9834L18.021 7.3974L9.414 16.0044H17V18.0044H6V7.0044H8V14.5894V14.5904Z" fill="currentColor"/>
    </svg>
  )
}
