// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/h-1.svg

import type { SVGProps } from 'react'

export function IconH1(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M13 20H11V13H4V20H2V4H4V11H11V4H13V20ZM21 8V20H19V10.204L17 10.74V8.67L19.5 8H21Z" fill="currentColor"/>
    </svg>
  )
}
