// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/trademark-fill.svg

import type { SVGProps } from 'react'

export function IconTrademarkFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M10 6V8H6V18H4V8H0V6H10ZM12 6H14.5L17.5 11.196L20.5 6H23V18H21V9.133L17.5 15.196L14 9.135V18H12V6Z" fill="currentColor"/>
    </svg>
  )
}
