// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-left-s-fill.svg

import type { SVGProps } from 'react'

export function IconArrowLeftSFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M8 12L14 6V18L8 12Z" fill="currentColor"/>
    </svg>
  )
}
