// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/terminal-fill.svg

import type { SVGProps } from 'react'

export function IconTerminalFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M10.9999 12.0001L3.92889 19.0711L2.51489 17.6571L8.17189 12.0001L2.51489 6.34305L3.92889 4.93005L10.9999 12.0001ZM10.9999 19.0001H20.9999V21.0001H10.9999V19.0001Z" fill="currentColor"/>
    </svg>
  )
}
