// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/functions.svg

import type { SVGProps } from 'react'

export function IconFunctions(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M5 18L12.68 12L5 6V4H19V6H8.263L16 12L8.263 18H19V20H5V18Z" fill="currentColor"/>
    </svg>
  )
}
