// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-left-down-fill.svg

import type { SVGProps } from 'react'

export function IconArrowLeftDownFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12.36 13.0504L17.31 18.0004H5.99805V6.68845L10.948 11.6384L16.604 5.98145L18.019 7.39545L12.36 13.0504Z" fill="currentColor"/>
    </svg>
  )
}
