// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-down-fill.svg

import type { SVGProps } from 'react'

export function IconArrowDownFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M13 12H20L12 20L4 12H11V4H13V12Z" fill="currentColor"/>
    </svg>
  )
}
