// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/contacts-book-upload-fill.svg

import type { SVGProps } from 'react'

export function IconContactsBookUploadFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M7 2V22H3V2H7ZM19.005 2C20.107 2 21 2.898 21 3.99V20.01C21 21.109 20.107 22 19.005 22H9V2H19.005ZM15 8L11 12H14V16H16V12H19L15 8ZM24 12V16H22V12H24ZM24 6V10H22V6H24Z" fill="currentColor"/>
    </svg>
  )
}
