// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/menu-unfold-fill.svg

import type { SVGProps } from 'react'

export function IconMenuUnfoldFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M21 17.9998V19.9998H3V17.9998H21ZM17.05 3.5498L22 8.4998L17.05 13.4498V3.5498ZM12 10.9998V12.9998H3V10.9998H12ZM12 3.9998V5.9998H3V3.9998H12Z" fill="currentColor"/>
    </svg>
  )
}
