// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-drop-right-fill.svg

import type { SVGProps } from 'react'

export function IconArrowDropRightFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M14 12L10 16V8L14 12Z" fill="currentColor"/>
    </svg>
  )
}
