// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/heading.svg

import type { SVGProps } from 'react'

export function IconHeading(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M17 11V4H19V21H17V13H7V21H5V4H7V11H17Z" fill="currentColor"/>
    </svg>
  )
}
