// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/luggage-deposit-fill.svg

import type { SVGProps } from 'react'

export function IconLuggageDepositFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M15 3C15.552 3 16 3.448 16 4V6H20C20.552 6 21 6.448 21 7V19H23V21H1V19H3V7C3 6.448 3.448 6 4 6H8V4C8 3.448 8.448 3 9 3H15ZM10 8H8V19H10V8ZM16 8H14V19H16V8ZM14 5H10V6H14V5Z" fill="currentColor"/>
    </svg>
  )
}
