// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/twitch-line.svg

import type { SVGProps } from 'react'

export function IconTwitchLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M4.3 3H21V14.7L16.3 19.4H12.4L9.9 21.8H7V19.4H3V6.2L4.3 3ZM5 17.4H9V19.8H9.095L11.595 17.4H15.472L19 13.872V5H5V17.4ZM15 8H17V12.7H15V8ZM15 8H17V12.7H15V8ZM10 8H12V12.7H10V8Z" fill="currentColor"/>
    </svg>
  )
}
