// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/building-3-line.svg

import type { SVGProps } from 'react'

export function IconBuilding3Line(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M10 10.111V1L21 7V21H3V7L10 10.111ZM12 4.369V13.189L5 10.078V19H19V8.187L12 4.37V4.369Z" fill="currentColor"/>
    </svg>
  )
}
