// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/macbook-fill.svg

import type { SVGProps } from 'react'

export function IconMacbookFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M2 4.007C2 3.45 2.455 3 2.992 3H21.008C21.556 3 22 3.45 22 4.007V17H2V4.007ZM1 19H23V21H1V19Z" fill="currentColor"/>
    </svg>
  )
}
