// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/heart-2-fill.svg

import type { SVGProps } from 'react'

export function IconHeart2Fill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M20.243 4.75699C22.505 7.02499 22.583 10.637 20.479 12.993L11.999 21.485L3.52101 12.993C1.41701 10.637 1.49601 7.01899 3.75701 4.75699C5.51501 2.99999 8.09301 2.55999 10.261 3.43999L6.34301 7.35799L7.75701 8.77299L12 4.52999L11.987 4.51599L12.001 4.52899C14.35 2.41999 17.98 2.48999 20.243 4.75699Z" fill="currentColor"/>
    </svg>
  )
}
