// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/filter-2-fill.svg

import type { SVGProps } from 'react'

export function IconFilter2Fill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M10 14L4 5V3H20V5L14 14V20L10 22V14Z" fill="currentColor"/>
    </svg>
  )
}
