// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/flashlight-fill.svg

import type { SVGProps } from 'react'

export function IconFlashlightFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M13 10H20L11 23V14H4L13 1V10Z" fill="currentColor"/>
    </svg>
  )
}
