// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/vip-crown-fill.svg

import type { SVGProps } from 'react'

export function IconVipCrownFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M2 19H22V21H2V19ZM2 5L7 8L12 2L17 8L22 5V17H2V5Z" fill="currentColor"/>
    </svg>
  )
}
