// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-drop-down-fill.svg

import type { SVGProps } from 'react'

export function IconArrowDropDownFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12 14L8 10H16L12 14Z" fill="currentColor"/>
    </svg>
  )
}
