// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/login-circle-fill.svg

import type { SVGProps } from 'react'

export function IconLoginCircleFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M10 11H2.05005C2.55005 5.947 6.81405 2 12 2C17.523 2 22 6.477 22 12C22 17.523 17.523 22 12 22C6.81505 22 2.55105 18.053 2.05005 13H10V16L15 12L10 8V11Z" fill="currentColor"/>
    </svg>
  )
}
