// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-drop-left-line.svg

import type { SVGProps } from 'react'

export function IconArrowDropLeftLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11.828 11.9998L14.657 14.8278L13.243 16.2428L9 11.9998L13.243 7.75684L14.657 9.17184L11.828 11.9998Z" fill="currentColor"/>
    </svg>
  )
}
