// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/netflix-line.svg

import type { SVGProps } from 'react'

export function IconNetflixLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M15.984 17.208L16 2H18V22C17.3528 21.7414 16.6731 21.5732 15.98 21.5L8 6.302V21.5C7.31312 21.5717 6.6398 21.74 6 22V2H8L15.984 17.208Z" fill="currentColor"/>
    </svg>
  )
}
