// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/code-s-line.svg

import type { SVGProps } from 'react'

export function IconCodeSLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M24 12L18.343 17.657L16.929 16.243L21.172 12L16.929 7.75702L18.343 6.34302L24 12ZM2.828 12L7.071 16.243L5.657 17.657L0 12L5.657 6.34302L7.07 7.75702L2.828 12Z" fill="currentColor"/>
    </svg>
  )
}
