// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/pulse-fill.svg

import type { SVGProps } from 'react'

export function IconPulseFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M9 7.53906L15 21.5391L18.659 13.0001H23V11.0001H17.341L15 16.4611L9 2.46106L5.341 11.0001H1V13.0001H6.659L9 7.53906Z" fill="currentColor"/>
    </svg>
  )
}
