// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/filter-2-line.svg

import type { SVGProps } from 'react'

export function IconFilter2Line(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M14 14V20L10 22V14L4 5V3H20V5L14 14ZM6.404 5L12 13.394L17.596 5H6.404Z" fill="currentColor"/>
    </svg>
  )
}
