// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/number-7.svg

import type { SVGProps } from 'react'

export function IconNumber7(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M19 2V3.5L10.763 22H8.574L16.587 4H6V2H19Z" fill="currentColor"/>
    </svg>
  )
}
