// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/shut-down-fill.svg

import type { SVGProps } from 'react'

export function IconShutDownFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11 2.05005V12H13V2.05005C18.053 2.55105 22 6.81505 22 12C22 17.523 17.523 22 12 22C6.477 22 2 17.523 2 12C2 6.81505 5.947 2.55105 11 2.05005Z" fill="currentColor"/>
    </svg>
  )
}
