// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-right-fill.svg

import type { SVGProps } from 'react'

export function IconArrowRightFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12 13H4V11H12V4L20 12L12 20V13Z" fill="currentColor"/>
    </svg>
  )
}
