// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/building-3-fill.svg

import type { SVGProps } from 'react'

export function IconBuilding3Fill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M10 10.111V1L21 7V21H3V7L10 10.111Z" fill="currentColor"/>
    </svg>
  )
}
