// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-right-s-line.svg

import type { SVGProps } from 'react'

export function IconArrowRightSLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M13.1719 11.9997L8.22192 7.04974L9.63592 5.63574L15.9999 11.9997L9.63592 18.3637L8.22192 16.9497L13.1719 11.9997Z" fill="currentColor"/>
    </svg>
  )
}
