// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-drop-down-line.svg

import type { SVGProps } from 'react'

export function IconArrowDropDownLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12.0001 14.9998L7.75708 10.7568L9.17208 9.34277L12.0001 12.1718L14.8281 9.34277L16.2431 10.7568L12.0001 14.9998Z" fill="currentColor"/>
    </svg>
  )
}
