// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/menu-fold-fill.svg

import type { SVGProps } from 'react'

export function IconMenuFoldFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M21 17.9998V19.9998H3V17.9998H21ZM6.95 3.5498V13.4498L2 8.4998L6.95 3.5498ZM21 10.9998V12.9998H12V10.9998H21ZM21 3.9998V5.9998H12V3.9998H21Z" fill="currentColor"/>
    </svg>
  )
}
