// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-left-up-fill.svg

import type { SVGProps } from 'react'

export function IconArrowLeftUpFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12.3601 10.9471L18.0181 16.6031L16.6031 18.0181L10.9471 12.3611L5.99707 17.3111V5.99707H17.3101L12.3601 10.9471Z" fill="currentColor"/>
    </svg>
  )
}
