// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/quill-pen-fill.svg

import type { SVGProps } from 'react'

export function IconQuillPenFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M21 2C6 2 4 16 3 22H4.998C5.664 18.667 7.331 16.834 10 16.5C14 16 17 12.5 18 9.5L16.5 8.5L17.5 7.5C18.5 6.5 19.504 5 21 2Z" fill="currentColor"/>
    </svg>
  )
}
