// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/vuejs-line.svg

import type { SVGProps } from 'react'

export function IconVuejsLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M3.316 3L12 18L20.684 3H23L12 22L1 3H3.316ZM7.658 3L12 10.5L16.342 3H18.658L12 14.5L5.342 3H7.658Z" fill="currentColor"/>
    </svg>
  )
}
