// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/settings-6-fill.svg

import type { SVGProps } from 'react'

export function IconSettings6Fill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M17.5 2.47363L23 11.9996L17.5 21.5256H6.5L1 11.9996L6.5 2.47363H17.5ZM8.634 8.16963L13.634 16.8296L15.366 15.8296L10.366 7.16963L8.634 8.16963Z" fill="currentColor"/>
    </svg>
  )
}
