// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/slice-fill.svg

import type { SVGProps } from 'react'

export function IconSliceFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M13.7681 12.232L15.8891 14.354C11.2931 18.95 5.63607 20.364 2.10107 19.657L17.6571 4.09998L19.7781 6.21998L13.7681 12.231V12.232Z" fill="currentColor"/>
    </svg>
  )
}
