// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/number-4.svg

import type { SVGProps } from 'react'

export function IconNumber4(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M16 1.5V16H19V18H16V22H14V18H4V16.898L14 1.5H16ZM14 16V5.171L6.968 16H14Z" fill="currentColor"/>
    </svg>
  )
}
