// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/unsplash-fill.svg

import type { SVGProps } from 'react'

export function IconUnsplashFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M8.5 11V16H15.5V11H21V21H3V11H8.5ZM15.5 3V8H8.5V3H15.5Z" fill="currentColor"/>
    </svg>
  )
}
