// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-up-fill.svg

import type { SVGProps } from 'react'

export function IconArrowUpFill(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M13 12V20H11V12H4L12 4L20 12H13Z" fill="currentColor"/>
    </svg>
  )
}
