// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/medicine-bottle-line.svg

import type { SVGProps } from 'react'

export function IconMedicineBottleLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M19 2V4H17V7C18.657 7 20 8.343 20 10V21C20 21.552 19.552 22 19 22H5C4.448 22 4 21.552 4 21V10C4 8.343 5.343 7 7 7V4H5V2H19ZM17 9H7C6.448 9 6 9.448 6 10V20H18V10C18 9.448 17.552 9 17 9ZM13 11V13H15V15H12.999L13 17H11L10.999 15H9V13H11V11H13ZM15 4H9V7H15V4Z" fill="currentColor"/>
    </svg>
  )
}
