// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/npmjs-line.svg

import type { SVGProps } from 'react'

export function IconNpmjsLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M20 3C20.552 3 21 3.448 21 4V20C21 20.552 20.552 21 20 21H4C3.448 21 3 20.552 3 20V4C3 3.448 3.448 3 4 3H20ZM19 5H5V19H19V5ZM17 7V17H14.5V9.5H12V17H7V7H17Z" fill="currentColor"/>
    </svg>
  )
}
