// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/door-closed-line.svg

import type { SVGProps } from 'react'

export function IconDoorClosedLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M3 21V19H5V4C5 3.448 5.448 3 6 3H18C18.552 3 19 3.448 19 4V19H21V21H3ZM17 5H7V19H17V5ZM15 11V13H13V11H15Z" fill="currentColor"/>
    </svg>
  )
}
