// AUTO-GENERATED by scripts/generate-icon-components.mjs. Do not edit by hand.
// Source SVG: assets/icons/arrow-drop-up-line.svg

import type { SVGProps } from 'react'

export function IconArrowDropUpLine(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12.0001 11.828L9.17208 14.657L7.75708 13.243L12.0001 9L16.2431 13.243L14.8281 14.657L12.0001 11.828Z" fill="currentColor"/>
    </svg>
  )
}
