import type { Metadata } from 'next'
import {
  colors,
  spacing as spacingTokens,
  radius as radiusTokens,
} from '../../style-tokens'

export const metadata: Metadata = {
  title: 'Design Tokens — Thingspire UI',
  description:
    'Browse every theme color, primitive palette, typography, spacing, and radius variable. Auto-generated from style-tokens.ts.',
}

// ─── Recursive token flattener ───────────────────────────────────────────────
type LeafEntry = {
  path: string[]
  name: string
  value: string | number
}

function flatten(node: unknown, basePath: string[] = []): LeafEntry[] {
  if (node === null || node === undefined) return []
  if (typeof node === 'string' || typeof node === 'number') {
    // Leaf placed at the parent path; the immediate key is the "name"
    return [{ path: basePath.slice(0, -1), name: basePath.at(-1) ?? '', value: node }]
  }
  if (Array.isArray(node) || typeof node !== 'object') return []
  const out: LeafEntry[] = []
  for (const [key, value] of Object.entries(node)) {
    out.push(...flatten(value, [...basePath, key]))
  }
  return out
}

function groupByPath(entries: LeafEntry[]): Map<string, LeafEntry[]> {
  const map = new Map<string, LeafEntry[]>()
  for (const entry of entries) {
    const key = entry.path.join(' / ') || '(root)'
    if (!map.has(key)) map.set(key, [])
    map.get(key)!.push(entry)
  }
  return map
}

// ─── Build collections ──────────────────────────────────────────────────────
const colorEntries = flatten(colors).filter(
  // Skip the `semantic.component.*` duplicate of `semantic.theme.*`.
  (e) => !(e.path[0] === 'semantic' && e.path[1] === 'component'),
)
const colorGroups = groupByPath(colorEntries)

// ─── Theme light/dark modes ─────────────────────────────────────────────────
// `colors.semantic.theme.{light,dark}` carry the full role-token set per mode
// (generated by scripts/generate-theme-modes.mjs). We render them together so
// every role token shows its Light and Dark value, with a toggle to switch.
type ThemeRow = { path: string[]; name: string; light: string; dark: string }

function buildThemeModes(): { groups: Map<string, ThemeRow[]>; hasModes: boolean } {
  const theme = (colors as { semantic?: { theme?: Record<string, unknown> } }).semantic?.theme
  const light = theme?.light
  const dark = theme?.dark
  if (!light || !dark) return { groups: new Map(), hasModes: false }

  const darkLookup = new Map(
    flatten(dark).map((e) => [[...e.path, e.name].join('/'), String(e.value)] as const),
  )
  const rows: ThemeRow[] = flatten(light).map((e) => {
    const key = [...e.path, e.name].join('/')
    return {
      path: e.path,
      name: e.name,
      light: String(e.value),
      dark: darkLookup.get(key) ?? String(e.value),
    }
  })

  const groups = new Map<string, ThemeRow[]>()
  for (const row of rows) {
    const key = row.path.join(' / ') || '(root)'
    if (!groups.has(key)) groups.set(key, [])
    groups.get(key)!.push(row)
  }
  return { groups, hasModes: true }
}

const { groups: themeModeGroups, hasModes } = buildThemeModes()
const themeRowCount = Array.from(themeModeGroups.values()).reduce((s, r) => s + r.length, 0)

// Primitive-only color groups for the generic section (theme is rendered on its
// own with the light/dark toggle, so drop every `semantic / theme / *` group).
const primitiveColorGroups = Array.from(colorGroups).filter(([key]) =>
  key.startsWith('primitive'),
)

// ─── Alias resolution ──────────────────────────────────────────────────────
// style-tokens.ts is fully resolved (every leaf is a hex), so the original
// Figma alias chain (e.g. background/button/primary → semantic/neutral/12) is
// flattened away. Reconstruct it by reverse-lookup on hex values: a primitive
// or semantic.theme.semantic token with the same hex is the source the
// downstream token most likely references.

const ALIAS_SOURCE_PREFIXES = [
  ['primitive'],
  ['semantic', 'theme', 'semantic'],
]

function isAliasSource(path: string[]): boolean {
  return ALIAS_SOURCE_PREFIXES.some((prefix) =>
    prefix.every((segment, i) => path[i] === segment),
  )
}

function shortenAliasPath(path: string[], name: string): string {
  // Strip the verbose root segments so the Figma-style "semantic/neutral/12"
  // shape comes through.
  let p = [...path, name]
  if (p[0] === 'primitive' && p[1] === 'palette') {
    p = ['palette', ...p.slice(2)]
  } else if (p[0] === 'semantic' && p[1] === 'theme') {
    p = p.slice(2)
  }
  return p.join('/')
}

// hex → first-seen source path
const aliasMap = new Map<string, { displayPath: string; hex: string }>()
for (const entry of colorEntries) {
  if (typeof entry.value !== 'string') continue
  if (!isAliasSource([...entry.path, entry.name])) continue
  if (!aliasMap.has(entry.value)) {
    aliasMap.set(entry.value, {
      displayPath: shortenAliasPath(entry.path, entry.name),
      hex: entry.value,
    })
  }
}

function getAlias(entry: LeafEntry): { displayPath: string; hex: string } | undefined {
  if (typeof entry.value !== 'string') return undefined
  if (isAliasSource([...entry.path, entry.name])) return undefined
  return aliasMap.get(entry.value)
}

const spacingEntries = flatten(spacingTokens)
const spacingGroups = groupByPath(spacingEntries)

const radiusEntries = flatten(radiusTokens)
const radiusGroups = groupByPath(radiusEntries)

// Hardcoded typography scale (the deeper tree is redundant — these are the
// surface tokens designers refer to)
const TYPOGRAPHY_GROUPS: Array<{ path: string[]; rows: LeafEntry[] }> = [
  {
    path: ['typography', 'family'],
    rows: [{ path: ['typography', 'family'], name: 'inter', value: 'Pretendard' }],
  },
  {
    path: ['typography', 'weight'],
    rows: [
      'Light',
      'Regular',
      'Medium',
      'Semi Bold',
      'Bold',
      'Extra Bold',
      'Black',
    ].map((label) => ({
      path: ['typography', 'weight'],
      name: label.toLowerCase().replace(/\s+/g, '-'),
      value: label,
    })),
  },
  {
    path: ['typography', 'size'],
    rows: [
      ['display', 96],
      ['h1', 72],
      ['h2', 64],
      ['h3', 48],
      ['h4', 36],
      ['h5', 30],
      ['h6', 24],
      ['body-l', 20],
      ['body-m', 18],
      ['body-s', 16],
      ['caption-l', 14],
      ['caption-m', 12],
      ['caption-s', 10],
    ].map(([name, value]) => ({
      path: ['typography', 'size'],
      name: name as string,
      value: `${value}px`,
    })),
  },
  {
    path: ['typography', 'line-height'],
    rows: [
      ['display', 100],
      ['h1', 80],
      ['h2', 56],
      ['h3', 44],
      ['h4', 36],
      ['h5', 36],
      ['h6', 32],
      ['body-l', 28],
      ['body-m', 26],
      ['body-s', 24],
      ['caption-l', 20],
      ['caption-m', 16],
      ['caption-s', 14],
    ].map(([name, value]) => ({
      path: ['typography', 'line-height'],
      name: name as string,
      value: `${value}px`,
    })),
  },
]

// ─── Build sidebar tree ─────────────────────────────────────────────────────
type SidebarGroup = { id: string; label: string; count: number }
type SidebarCollection = {
  id: string
  label: string
  count: number
  groups: SidebarGroup[]
}

function buildCollection(
  id: string,
  label: string,
  groupMap: Map<string, LeafEntry[]>,
  pathPrefix?: string,
): SidebarCollection {
  const groups: SidebarGroup[] = []
  for (const [groupKey, rows] of groupMap) {
    if (pathPrefix && !groupKey.startsWith(pathPrefix)) continue
    const groupId = `g-${groupKey.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`
    groups.push({
      id: groupId,
      label: groupKey.replace(/^.+? \/ /, ''),
      count: rows.length,
    })
  }
  return {
    id,
    label,
    count: groups.reduce((sum, g) => sum + g.count, 0),
    groups,
  }
}

const themeGroupId = (groupKey: string) =>
  `g-theme-${groupKey.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`

const COLLECTIONS: SidebarCollection[] = [
  buildCollection('primitive', 'Primitive', colorGroups, 'primitive'),
  {
    id: 'theme',
    label: 'Theme · Light / Dark',
    count: themeRowCount,
    groups: Array.from(themeModeGroups, ([groupKey, rows]) => ({
      id: themeGroupId(groupKey),
      label: groupKey,
      count: rows.length,
    })),
  },
  {
    id: 'typography',
    label: 'Typography',
    count: TYPOGRAPHY_GROUPS.reduce((s, g) => s + g.rows.length, 0),
    groups: TYPOGRAPHY_GROUPS.map((g) => ({
      id: `g-${g.path.join('-')}`,
      label: g.path.at(-1)!,
      count: g.rows.length,
    })),
  },
  {
    id: 'spacing',
    label: 'Spacing',
    count: spacingEntries.length,
    groups: Array.from(spacingGroups, ([key, rows]) => ({
      id: `g-spacing-${key.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`,
      label: key.split(' / ').slice(-1).join(''),
      count: rows.length,
    })),
  },
  {
    id: 'radius',
    label: 'Radius',
    count: radiusEntries.length,
    groups: Array.from(radiusGroups, ([key, rows]) => ({
      id: `g-radius-${key.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`,
      label: key.split(' / ').slice(-1).join('') || 'radius',
      count: rows.length,
    })),
  },
]

// ─── Render helpers ─────────────────────────────────────────────────────────
function isHexColor(v: unknown): v is string {
  return typeof v === 'string' && /^#[0-9a-fA-F]{6,8}$/.test(v)
}

function GroupTable({
  groupKey,
  rows,
  groupId,
}: {
  groupKey: string
  rows: LeafEntry[]
  groupId: string
}) {
  const sample = rows[0]?.value
  const isColors = isHexColor(sample)
  const valueLabel = isColors ? 'Value' : 'Value'

  // Display path with last segment bold
  const parts = groupKey.split(' / ')
  const last = parts.pop()

  return (
    <div id={groupId} style={{ scrollMarginTop: 80, marginBottom: 40 }}>
      <div
        style={{
          fontSize: 12,
          color: 'hsl(var(--muted-foreground))',
          marginBottom: 10,
          paddingInline: 16,
        }}
      >
        {parts.length ? `${parts.join(' / ')} / ` : ''}
        <strong style={{ color: 'hsl(var(--foreground))' }}>{last}</strong>{' '}
        <span style={{ color: 'hsl(var(--muted-foreground))' }}>· {rows.length}</span>
      </div>
      <table className="vars-table">
        <thead>
          <tr>
            <th style={{ width: '46%' }}>Name</th>
            <th>{valueLabel}</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => {
            const value = String(row.value)
            const isColor = isHexColor(row.value)
            return (
              <tr key={`${groupId}-${row.name}`}>
                <td>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                    {isColor ? (
                      <span
                        aria-hidden
                        style={{
                          display: 'inline-block',
                          width: 18,
                          height: 18,
                          borderRadius: 4,
                          background: value,
                          border: '1px solid hsl(var(--border))',
                          flexShrink: 0,
                        }}
                      />
                    ) : (
                      <span
                        aria-hidden
                        style={{
                          display: 'inline-flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          width: 18,
                          height: 18,
                          borderRadius: 3,
                          border: '1px solid hsl(var(--border))',
                          fontSize: 10,
                          color: 'hsl(var(--muted-foreground))',
                          flexShrink: 0,
                        }}
                      >
                        T
                      </span>
                    )}
                    <code style={{ fontSize: 13 }}>{row.name}</code>
                  </div>
                </td>
                <td>
                  {(() => {
                    const alias = getAlias(row)
                    if (alias) {
                      return (
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                          <span className="vars-alias-chip">
                            <span
                              aria-hidden
                              style={{
                                display: 'inline-block',
                                width: 14,
                                height: 14,
                                borderRadius: 3,
                                background: alias.hex,
                                border: '1px solid hsl(var(--border))',
                              }}
                            />
                            <code style={{ fontSize: 12 }}>{alias.displayPath}</code>
                          </span>
                          <code
                            style={{
                              fontSize: 12,
                              color: 'hsl(var(--muted-foreground))',
                            }}
                          >
                            {value}
                          </code>
                        </div>
                      )
                    }
                    return <code style={{ fontSize: 13 }}>{value}</code>
                  })()}
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

function Swatch({ hex }: { hex: string }) {
  return (
    <span
      aria-hidden
      style={{
        display: 'inline-block',
        width: 18,
        height: 18,
        borderRadius: 4,
        background: hex,
        border: '1px solid hsl(var(--border))',
        flexShrink: 0,
      }}
    />
  )
}

// Theme group table: every role token shows both its Light and Dark value; the
// segmented toggle (CSS-only, see .theme-modes in globals.css) reveals one at a
// time without needing a client component.
function ThemeGroupTable({ groupKey, rows }: { groupKey: string; rows: ThemeRow[] }) {
  const groupId = themeGroupId(groupKey)
  return (
    <div id={groupId} style={{ scrollMarginTop: 80, marginBottom: 40 }}>
      <div
        style={{
          fontSize: 12,
          color: 'hsl(var(--muted-foreground))',
          marginBottom: 10,
          paddingInline: 16,
        }}
      >
        <strong style={{ color: 'hsl(var(--foreground))' }}>{groupKey}</strong>{' '}
        <span style={{ color: 'hsl(var(--muted-foreground))' }}>· {rows.length}</span>
      </div>
      <table className="vars-table">
        <thead>
          <tr>
            <th style={{ width: '46%' }}>Name</th>
            <th>
              Value <span className="theme-modes__active-label" />
            </th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={`${groupId}-${row.name}`}>
              <td>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <span className="theme-val theme-val--light">
                    <Swatch hex={row.light} />
                  </span>
                  <span className="theme-val theme-val--dark">
                    <Swatch hex={row.dark} />
                  </span>
                  <code style={{ fontSize: 13 }}>{row.name}</code>
                </div>
              </td>
              <td>
                <code className="theme-val theme-val--light" style={{ fontSize: 13 }}>
                  {row.light}
                </code>
                <code className="theme-val theme-val--dark" style={{ fontSize: 13 }}>
                  {row.dark}
                </code>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// ─── Page ───────────────────────────────────────────────────────────────────
export default function TokensPage() {
  // Order: primitive groups alphabetically (theme is rendered separately below).
  const orderedPrimitiveGroups = primitiveColorGroups
    .slice()
    .sort(([a], [b]) => a.localeCompare(b))

  const totalEntries =
    primitiveColorGroups.reduce((s, [, rows]) => s + rows.length, 0) +
    themeRowCount +
    TYPOGRAPHY_GROUPS.reduce((s, g) => s + g.rows.length, 0) +
    spacingEntries.length +
    radiusEntries.length

  return (
    <div className="vars-page">
      <aside className="vars-sidebar">
        <div className="vars-sidebar__heading">Collections</div>
        <nav>
          {COLLECTIONS.map((col) => (
            <div key={col.id} style={{ marginBottom: 14 }}>
              <a
                href={col.groups[0] ? `#${col.groups[0].id}` : '#'}
                className="vars-sidebar__row vars-sidebar__row--collection"
              >
                <span>{col.label}</span>
                <span className="vars-sidebar__count">{col.count}</span>
              </a>
              {col.groups.map((g) => (
                <a
                  key={g.id}
                  href={`#${g.id}`}
                  className="vars-sidebar__row vars-sidebar__row--group"
                  title={g.label}
                >
                  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {g.label}
                  </span>
                  <span className="vars-sidebar__count">{g.count}</span>
                </a>
              ))}
            </div>
          ))}
        </nav>
      </aside>

      <main className="vars-main">
        <header className="vars-main__header">
          <h1 style={{ margin: 0, fontSize: 22, fontWeight: 600, letterSpacing: '-0.01em' }}>
            Variables
          </h1>
          <p style={{ margin: '4px 0 0', fontSize: 13, color: 'hsl(var(--muted-foreground))' }}>
            {totalEntries.toLocaleString()} tokens — generated from{' '}
            <code>style-tokens.ts</code>. Browse by collection on the left.
          </p>
        </header>

        {/* Primitive color groups */}
        {orderedPrimitiveGroups.map(([groupKey, rows]) => {
          const groupId = `g-${groupKey.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`
          return <GroupTable key={groupId} groupId={groupId} groupKey={groupKey} rows={rows} />
        })}

        {/* Theme — Light / Dark modes with a CSS-only toggle */}
        {hasModes && (
          <section className="theme-modes" id="g-theme">
            <input type="radio" name="theme-mode" id="theme-mode-light" defaultChecked />
            <input type="radio" name="theme-mode" id="theme-mode-dark" />
            <div className="theme-modes__bar">
              <div>
                <div style={{ fontSize: 15, fontWeight: 600 }}>Theme</div>
                <div style={{ fontSize: 12, color: 'hsl(var(--muted-foreground))' }}>
                  Semantic role tokens — switch between Light and Dark.
                </div>
              </div>
              <div className="theme-modes__toggle" role="group" aria-label="Theme mode">
                <label htmlFor="theme-mode-light" className="theme-modes__btn">
                  Light
                </label>
                <label htmlFor="theme-mode-dark" className="theme-modes__btn">
                  Dark
                </label>
              </div>
            </div>
            <div className="theme-modes__body">
              {Array.from(themeModeGroups).map(([groupKey, rows]) => (
                <ThemeGroupTable key={groupKey} groupKey={groupKey} rows={rows} />
              ))}
            </div>
          </section>
        )}

        {/* Typography */}
        {TYPOGRAPHY_GROUPS.map((group) => {
          const groupId = `g-${group.path.join('-')}`
          return (
            <GroupTable
              key={groupId}
              groupId={groupId}
              groupKey={group.path.join(' / ')}
              rows={group.rows}
            />
          )
        })}

        {/* Spacing */}
        {Array.from(spacingGroups).map(([groupKey, rows]) => {
          const groupId = `g-spacing-${groupKey.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`
          return (
            <GroupTable
              key={groupId}
              groupId={groupId}
              groupKey={`spacing / ${groupKey}`}
              rows={rows.map((r) => ({ ...r, value: typeof r.value === 'number' ? `${r.value}px` : r.value }))}
            />
          )
        })}

        {/* Radius */}
        {Array.from(radiusGroups).map(([groupKey, rows]) => {
          const groupId = `g-radius-${groupKey.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`
          return (
            <GroupTable
              key={groupId}
              groupId={groupId}
              groupKey={`radius / ${groupKey}`}
              rows={rows.map((r) => ({
                ...r,
                value:
                  typeof r.value === 'number'
                    ? r.value === 999
                      ? '999px (full)'
                      : `${r.value}px`
                    : r.value,
              }))}
            />
          )
        })}
      </main>
    </div>
  )
}
