#!/usr/bin/env node
/* Generates `src/index.ts` (component barrel) for the @309-thingspire/dsg
 * npm package. Reads `components/catalog.json`, then for each entry parses
 * the component's main `.tsx` file to find its named exports.
 *
 * Output is sorted alphabetically and includes a header banner so it's
 * obvious it should not be hand-edited.
 *
 * Usage: node scripts/generate-barrel.mjs
 *   (also runs as `prebuild` step before `tsup`)
 */
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT = path.resolve(__dirname, '..')

const CATALOG = path.join(ROOT, 'components', 'catalog.json')
const OUT = path.join(ROOT, 'src', 'index.ts')
const CATEGORIES = ['atoms', 'molecules', 'organisms']

const VALUE_EXPORT_RE = /export\s+(?:function|const|class|let|var)\s+([A-Z][\w]*)/g
const TYPE_EXPORT_RE = /export\s+(?:type|interface)\s+([A-Z][\w]*)/g
const RE_EXPORT_RE = /export\s*\{\s*([A-Z][\w]*)/g

async function readExports(filePath) {
  const src = await fs.readFile(filePath, 'utf-8')
  const values = new Set()
  const types = new Set()
  for (const match of src.matchAll(VALUE_EXPORT_RE)) values.add(match[1])
  for (const match of src.matchAll(TYPE_EXPORT_RE)) types.add(match[1])
  for (const match of src.matchAll(RE_EXPORT_RE)) values.add(match[1])
  return { values: [...values], types: [...types] }
}

async function main() {
  const catalog = JSON.parse(await fs.readFile(CATALOG, 'utf-8'))
  const lines = [
    '// AUTO-GENERATED by scripts/generate-barrel.mjs. Do not edit by hand.',
    '// Re-run `node scripts/generate-barrel.mjs` after adding a new component.',
    '',
  ]

  const entries = []
  for (const cat of CATEGORIES) {
    for (const item of catalog[cat] ?? []) {
      // Skip the icons aggregate — it has its own subpath export (./icons).
      if (item.slug === 'icons') continue
      const componentFile = path.join(ROOT, 'components', item.folder, `${item.folder}.tsx`)
      const typesFile = path.join(ROOT, 'components', item.folder, `${item.folder}.types.ts`)
      const componentExports = await readExports(componentFile)
      let typesFileExports = { values: [], types: [] }
      try {
        typesFileExports = await readExports(typesFile)
      } catch {
        /* types file optional */
      }
      entries.push({
        folder: item.folder,
        // Values from the component file (Component itself + any helpers)
        componentValues: componentExports.values,
        // Types from the component file (rare but possible)
        componentTypes: componentExports.types,
        // Values from .types.ts (e.g. const enums)
        typesValues: typesFileExports.values,
        // Types from .types.ts
        typesTypes: typesFileExports.types,
        hasTypesFile: typesFileExports.values.length + typesFileExports.types.length > 0,
      })
    }
  }

  entries.sort((a, b) => a.folder.localeCompare(b.folder))

  let valueCount = 0
  let typeCount = 0
  for (const { folder, componentValues, componentTypes, typesValues, typesTypes, hasTypesFile } of entries) {
    if (componentValues.length > 0) {
      lines.push(`export { ${componentValues.join(', ')} } from '../components/${folder}/${folder}'`)
      valueCount += componentValues.length
    }
    if (componentTypes.length > 0) {
      lines.push(`export type { ${componentTypes.join(', ')} } from '../components/${folder}/${folder}'`)
      typeCount += componentTypes.length
    }
    if (hasTypesFile) {
      if (typesValues.length > 0) {
        lines.push(`export { ${typesValues.join(', ')} } from '../components/${folder}/${folder}.types'`)
        valueCount += typesValues.length
      }
      if (typesTypes.length > 0) {
        lines.push(`export type { ${typesTypes.join(', ')} } from '../components/${folder}/${folder}.types'`)
        typeCount += typesTypes.length
      }
    }
  }

  lines.push('')
  await fs.mkdir(path.dirname(OUT), { recursive: true })
  await fs.writeFile(OUT, lines.join('\n'), 'utf-8')

  console.log(`✓ Wrote ${valueCount} value exports (+ ${typeCount} type exports) to src/index.ts`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
